### ISSUE TITLE
swc data to test with

### ISSUE THREAD

**Issue by zeffii** [MartinPyka/SWC2Blender#1]
Got any .swc files for me to experiment with?

**Comment by MartinPyka** [comment]
Here are two files, but you can download many other at 
http://neuromorpho.org/

Best,
Martin

**Comment by MartinPyka** [comment]
ok, sorry, for this post. was not aware, that my attachments would be depicted as plain text. added two example files to the repository.

**Comment by zeffii** [comment]
cool thank you!

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7962442/ab812d3e-0a0d-11e5-9877-664894123e05.png)

**Comment by MartinPyka** [comment]
do you have any issues? the entorhinal neuron has a long ranging projection. therefore it looks a bit wired. the other neurons looks much more like a "classical" neuron.

**Comment by zeffii** [comment]
no it works fine, I'd [use the csv importer](http://blender.stackexchange.com/a/31882/47) with ' ' delimiter though instead of rolling your own file parser..

**Comment by MartinPyka** [comment]
thanks for your suggestion. I was worried, that the csv-importer can't handle the comments and empty lines which usually precede the data. therefore, I used my own parser. but I will give it a try.

**Comment by zeffii** [comment]
Yes, that could be a problem. i'm trying now :)

**Comment by zeffii** [comment]
ok, after trying it is a little messy. never mind me.

**Comment by zeffii** [comment]
``` python
import csv
import os
import bpy

''' read swc file '''
filepath = '/home/zeffii/Downloads/swc/swc_files/entho.CNG.swc'
with open(filepath, 'r', newline='') as csvfile:
    ofile = csv.reader(csvfile, delimiter=' ')

    # this makes a generator of the remaining non-empty lines
    # assumes there's always a lead and trailing space.. [1:-1] , this may be evil
    rows = (r[1:-1] for r in ofile if r and not r[0].startswith('#'))

    # convert string representation of each line to dict of list-floats
    neurons = {float(r[0].strip()): [float(i) for i in r] for r in rows}

```

but i'm making assumptions here about the formatting of the file, which is probably not cool.

**Comment by MartinPyka** [comment]
hey, thanks for the code. When I am back at work, I will try to integrate it into the importer

**Comment by zeffii** [comment]
in any case you have a working importer, if the csv route fails there is no loss :)

**Comment by MartinPyka** [comment]
jep, the next step will be to integrate the code of https://github.com/ajayramak/BlenderSWCVizualizer into this addon. I am already in contact with ajayramak about that.

**Comment by zeffii** [comment]
another repo with no images!   :/

**Comment by MartinPyka** [comment]
changed that for my repo ;)

**Comment by zeffii** [comment]
as it should be. OK. back to work :)

**Comment by zeffii** [comment]
btw: 

```
rows = ([j for j in r if j] for r in ofile if r and not r[0].startswith('#'))
```

may be better, it doesn't assume anything, but does add iff the list item is not empty. I don't know if this is faster than your original code... it may not be..
