### ISSUE TITLE
SWC import not showing up in menu

### ISSUE THREAD

**Issue by kir0ul** [MartinPyka/SWC2Blender#2]
Hi,

I have the add-on which seems to be installed and activated:
![image](https://user-images.githubusercontent.com/6053592/69756519-b5855680-1128-11ea-8087-9d3ef4e6c0e4.png)

But for some reason the SWC option doesn't show up in the _Import_ menu:
![image](https://user-images.githubusercontent.com/6053592/69756585-df3e7d80-1128-11ea-8df6-1891573c85b5.png)

Is there anything I missed to make it work?
Thanks.

**Comment by MartinPyka** [comment]
hi,

no, you didn't miss anything. The first screenshot says "Upgrade to 2.8x required". So I guess, it is simply not working with 2.8 properly. I cannot say, when I am able to fix this. For the time being I would recommend to use this plugin with Blender 2.7x, import the model, save it as blend file and then use 2.8.

Best,
Martin

**Comment by kir0ul** [comment]
Works with Blender 2.7x, thanks 👍
